### ISSUE TITLE
mkpl enhancement: cache

### ISSUE THREAD

**Issue by bonelifer** [MatteoGuadrini/mkpl#10]
## Description
Cache added tracks

Description of the proposal
Add option to cache tracks added to playlist for specified time, so that they aren't available for adding to playlist till their cache period is over.

## Proposed names of the parameters (short and long)

* name parameter: cache
* possible argument(s): time(in days)
  * --cache (default when called with out the time):30 days)
  * --cache 60

**Comment by MatteoGuadrini** [comment]
Implemented `cache` option into new version **1.10.0**, to increase performance to build playlist in massive files folders
