### ISSUE TITLE
mkpl enhancement - Add argument (option) to replace spaces in filenames with %20 (space code)

### ISSUE THREAD

**Issue by masterofobzene** [MatteoGuadrini/mkpl#12]
## Description

Some files I have struggle to play on mpv, some contain ` ' ` or ` -` and this when coupled with spaces or double spaces like `somefile what' s going on  -seg01.mp3` (note the double spaces before -seg01 makes the player refuse to play.

## Proposed names of the parameters (short and long)

* name parameter = safe names
* possible argument(s) = --safe_names  (-sn)

Additional context

The idea is to pass the proposed "--safe_names" or "-sn" argument to replace spaces with %20 thus making the example file from above to be added like: `somefile%20what'%20s%20going%20on%20-seg01.mp3` thus making the file playable again and bypass mpv's strange tendency to read m3u entries as arguments if the files have spaces or special characters.

**Comment by MatteoGuadrini** [comment]
Hi @masterofobzene,
your idea is very beautiful. I like it.
In the next release I can implement it.
My suggestion is: `-U`, `--url-chars`
according to table W3: https://www.w3schools.com/tags/ref_urlencode.ASP

Thanks for the proposal

**Comment by MatteoGuadrini** [comment]
Implemented `url-chars` argument into new realese version **1.10.0**
