### ISSUE TITLE
[QUESTION] Can we put many file types in the -include arg?

### ISSUE THREAD

**Issue by masterofobzene** [MatteoGuadrini/mkpl#13]
Can we put many file types in the -include arg?

How does it work?

```
-i mkv;jpg

-i mkv jpg

-i mkv -i jpg

-i mkv,jpg
```

**Comment by MatteoGuadrini** [comment]
> Can we put many file types in the -include arg?
> 
> How does it work?
> 
> ```
> -i mkv;jpg
> 
> -i mkv jpg
> 
> -i mkv -i jpg
> 
> -i mkv,jpg
> ```
Isn't that already the case?

`usage: mkpl [-h] [-v] [-V] [-d DIRECTORIES [DIRECTORIES ...]] [-e EXCLUDE_DIRS [EXCLUDE_DIRS ...]] [-i FORMAT [FORMAT ...]] ...` 

as the help says, you can type as many extensions as you want with spaces:

```
cd myfolder && mkpl playlist1 -i mkv mp4 avi etc .src *.src2
```

As for extensions, you proposed image-type extensions within video formats... I don't think that's correct. As for the `mkv` format, I will include it in the defaults in the next release.

**Comment by MatteoGuadrini** [comment]
The word _format_ is used in files to identify the compatible format. Especially in the audio/video field, we talk about formats and not extensions. I think it's best to leave it as it is.
