### ISSUE TITLE
Order by Track

### ISSUE THREAD

**Issue by fiz1962** [MatteoGuadrini/mkpl#14]
When using -T (order by track) it treats the track number as text rather than an int and does not sort properly as a result.  The track order sorts as

1,10,11,12,...,19,2,20,21,...,etc

Fixed by converting track number to an int as below

def get_track(file):
    """Get file by track for sort"""
    file = open_multimedia_file(file)
    if file and hasattr(file, "tags"):
        default = id3.TRCK(text="0")
        return int(file.tags.get("TRCK", default)[0])

**Comment by MatteoGuadrini** [comment]
Hi @fiz1962,
You are right!
I'll do it right away.

**Comment by MatteoGuadrini** [comment]
Bug resolved into new version **1.10.0**
