### ISSUE TITLE
You can achieve the same with powershell

### ISSUE THREAD

**Issue by masterofobzene** [MatteoGuadrini/mkpl#15]
Hi, just to tell you, you can achieve the same results with powershell (make a playlist) and with **symbolic links support** (which mkpl doesn't)

You can use this command in a powershell console to get the playlist of a folder containing files. Mine has images and videos but you can change the desired extensions.

```
cd "C:\YOUR_MEDIA_FOLDER_PATH"

gci -recurse -Include *.mpg, *.mp4, *.mov, *.mpeg, *.m4v, *.3gp, *.flv, *.webm, *.avi, *.mkv, *.ts, *.wmv, *.jpeg, *.jpg, *.bmp, *.webp, *.gif, *.png, *.tiff| Resolve-Path -Relative | Sort-Object -Property {$_.Name -as [int]} | Out-File -Encoding UTF8 -FilePath '.\playlist.m3u' 
```

That will save a file with m3u extension with all the files. Works with MPV, I suppose with others too.

Linux bash should be even better for this as I've seen it having more filtering options and such, shouldn't be hard for a linux user to make a script like this.

**Comment by MatteoGuadrini** [comment]
Hi @masterofobzene, 
I don't understand where do you want to going with this explanation... `mkpl` do the same result...also on linux. I use everyday. 
If you use `mkpl` on Windows do not forget to use the flag `--windows` or `-w`; this convert the path symbols slash `/` to back-slash (`\`):
```-w	--windows	Windows style folder separator```

Maybe do not works for this in MPV.

But this project is not written in powershell and I do not want rewritten in powershell.

Thanks.
