### ISSUE TITLE
[Q&A/HELP] make m3u based on track ID? 

### ISSUE THREAD

**Issue by omaru-ok** [MatteoGuadrini/mkpl#3]
i have a huge music collection now , but the problem i did while ripping them is,  they have names that do no start with numbers 
, instead they start with music file names  , that's a problem , since [mpv](mpv.io) plays files based on alphatic order .

i just want `mkbl` to make m3u list of album i am going to play , in track number order  and feed to it mpv 

this are the some other post of same question : 
https://www.reddit.com/r/mpv/comments/10sp0ge/questionhelp_force_to_play_track_based_upon_track/

**Comment by MatteoGuadrini** [comment]
Hi @omaru-ok, this is a non `mkpl` issue. `mkpl` asks the file system for a list of media files in one or more given directories and creates a playlist file. Currently the order is returned by the file system of the operating system (try doing an `ls` and see in which order the files return).
Both `mkpl` and `mpv` do not look at mp3 tags for example, in which the track number is also written.

Execution ordering is about the order in which the file system returns things.

Unfortunately I can't do anything about this except implement two sort flags in `mkpl` as suggested by @aburchio in issue #4.
