### ISSUE TITLE
Shuffles order every time

### ISSUE THREAD

**Issue by aburchio** [MatteoGuadrini/mkpl#4]
I can't find a way to instruct mkpl to create playlist "in album order". 
it's like the "shuffle" option is always set. 
basically this is what happens:

$ cd Electric\ Light\ Orchestra\ \(1975\)\ Face\ The\ Music/

$ mkpl test.m3u

$ cat test.m3u 
11 - Strange Magic [Single Edit].m4a
01 - Fire On High.m4a
03 - Evil Woman.m4a
06 - Strange Magic.m4a
04 - Nightrider.m4a
07 - Down Home Town.m4a
05 - Poker.m4a
10 - Evil Woman [Stripped Down Mix].m4a
09 - Fire On High [Early Alternate Mix].m4a
12 - Waterfall [Instrumental Mix].m4a
08 - One Summer Dream.m4a
02 - Waterfall.m4a

**Comment by MatteoGuadrini** [comment]
Hi @aburchio, actually the order is not random, but it is returned from the file system directly. So if you make a list (`ls`) of the same directory, the order will be the same as the playlist.

I could implement two new flags:
- `-o`, `--orderby-name`: order list of multimedia files by name
- `-O`, `--orderby-date`: order list of multimedia files by creation date

It might solve the problem you discovered...

**Comment by life5ign** [comment]
Any chance of using a Python IDE/MP3 tag library to look at the track field, and order by that?

**Comment by aburchio** [comment]
> I could implement two new flags:
> 
>     * `-o`, `--orderby-name`: order list of multimedia files by name
> 
>     * `-O`, `--orderby-date`: order list of multimedia files by creation date

I have tried some commands after your reply and yes, some commands like 'find' will return the list in an unsorted order, while 'ls' seems to work fine  on my system. If you could implement some type of sorting it would be very useful, because mkpl would not rely on commands generated order, that could be wrong or confusing.
