### ISSUE TITLE
mkpl enhancement - Support .opus files

### ISSUE THREAD

**Issue by life5ign** [MatteoGuadrini/mkpl#5]
## Description

Description of the proposal

Enable support for OPUS format files.

## Proposed names of the parameters (short and long)

None needed.

* name parameter
* possible argument(s)

Additional context

This error is reported for a directory with `*.opus` files:

> warning: no multimedia files are found here: <directory>

**Comment by MatteoGuadrini** [comment]
Hi @life5ign, 
like explained in [Command arguments](https://github.com/MatteoGuadrini/mkpl#command-arguments) session, the `-i` or `--include` argument, _includes other formats_, for example:
```console
$  mkpl -d "folder1" "folder2" "folder3" -i opus "my_music.m3u"
```
However, it seems like a legitimate proposition and I will include in the default formats to the next minor release.

**Comment by life5ign** [comment]
Cool!  I actually tried using `--include`, but didn't read the README closely enough, and used ".opus" as the argument, so it didn't work, obviously.
