### ISSUE TITLE
mkpl enhancement: add ability to order playlist entries by file "track" metadata

### ISSUE THREAD

**Issue by life5ign** [MatteoGuadrini/mkpl#6]
## Description

Description of the proposal
See issue #4 for evolution of this idea.

It would be great to have the default be to order tracks lexically in playlists by their "track" tag/metadata, and then my filename if no metadata is found.  This default behavior could avoid having to specify a flag for this.  The use of a metadata parsing library could be extended to add filters as CLI flags, which would filter files based on metadata, for other enhancements, but this is perhaps an extension of the kernel of this enhancement.

## Proposed names of the parameters (short and long)

N/A, for this enhancement; posssibly `--order-by` with "filesystem" "metadata:track" as arguments, if it was absolutely necessary.
* name parameter: N/A
* possible argument(s) N/A

Additional context
See issue #4 as mentioned.

**Comment by life5ign** [comment]
I accidentally hit Ctrl+Enter to soon and created the issue without a description.  I just added it.  Thanks for entertaining the idea, @MatteoGuadrini !

**Comment by MatteoGuadrini** [comment]
Hi @life5ign, I introduce in the release 1.7.0 a new argument flag, `-T` or `--orderby-track` that order playlist by track number.

**Comment by life5ign** [comment]
Great, thanks @MatteoGuadrini!
